/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.View.members;

import com.DB.MembersDB;
import com.Objects.Members;
import javax.swing.JOptionPane;
import javax.swing.text.html.CSS;

/**
 *
 * @author diego
 */
public class MembersAdd extends javax.swing.JInternalFrame {

    /**
     * Creates new form MembersAdd
     */
    public MembersAdd() {
        initComponents();
        
    }
    
        public void addMembers(){
        
        try{
            String  memberId = textMemberID.getText() ;
            String  fName = textMemberFName.getText() ;
            String  lName = textMemberLName.getText() ;
            String  birthday = textMemberBirthday.getText() ;
            String  phoneNumber = textMemberPhoneNumber.getText() ;
            String  email = textMemberEmail.getText() ;
            String  street = textMemberStreet.getText() ;
            String  houseNumber =textMemberHouseNumber.getText() ;
            String  aircode = textMemberAircode.getText() ;
            String  city = textMemberCity.getText() ;
            String  country = textMemberCountry.getText() ;
            String  startDate = textMemberStartDate.getText() ;
            
            Members member = new Members();
            
            member.setId(memberId);
            member.setFirstName(fName);
            member.setLastName(lName);
            member.setBirthday(birthday);
            member.setCellPhone(phoneNumber);
            member.setEmail(email);
            member.setStreet(street);
            member.setHouseNumber(houseNumber);
            member.setAircode(aircode);
            member.setCity(city);
            member.setCountry(country);
            member.setStartDate(startDate);
            
            MembersDB memberDB = new MembersDB();
            boolean checkAdding = memberDB.addMember(member);
            
            if (checkAdding == true){
                JOptionPane.showMessageDialog(null, "Member Registered");
                
                textMemberID.setText(null);
                textMemberFName.setText(null);
                textMemberLName.setText(null);
                textMemberBirthday.setText(null);
                textMemberPhoneNumber.setText(null);
                textMemberEmail.setText(null);
                textMemberStreet.setText(null);
                textMemberHouseNumber.setText(null);
                textMemberAircode.setText(null);
                textMemberCity.setText(null);
                textMemberCountry.setText(null);
                textMemberStartDate.setText(null);              
                
            }
            
        }catch(Exception error){
            JOptionPane.showMessageDialog(null, "Button AddMember" + error.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textMemberID = new javax.swing.JTextField();
        textMemberLName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textMemberStartDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textMemberEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textMemberStreet = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textMemberAircode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textMemberHouseNumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textMemberCity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textMemberPhoneNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textMemberCountry = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textMemberBirthday = new javax.swing.JTextField();
        textMemberFName = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("New Member");
        setDesktopIcon(getDesktopIcon());
        setName("Insert User"); // NOI18N
        setPreferredSize(new java.awt.Dimension(560, 300));
        setVisible(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Number *");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setText("First Name *");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        textMemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMemberIDActionPerformed(evt);
            }
        });
        getContentPane().add(textMemberID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 160, -1));
        getContentPane().add(textMemberLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 170, -1));

        jLabel3.setText("Birthday");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        textMemberStartDate.setText("yyyy/mm/dd");
        textMemberStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMemberStartDateActionPerformed(evt);
            }
        });
        getContentPane().add(textMemberStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 102, -1));

        jLabel4.setText("E-mail");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        textMemberEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMemberEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textMemberEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 270, -1));

        jLabel5.setText("Street / Road");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));
        getContentPane().add(textMemberStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 296, -1));

        jLabel7.setText("AirCode");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));
        getContentPane().add(textMemberAircode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, -1));

        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel9.setText("Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));
        getContentPane().add(textMemberHouseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 70, -1));

        jLabel10.setText("City");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));
        getContentPane().add(textMemberCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 110, -1));

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 120, 70));
        getContentPane().add(textMemberPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, -1));

        jLabel11.setText("Country");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        textMemberCountry.setText("Ireland");
        getContentPane().add(textMemberCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 130, -1));

        jLabel6.setText("Last Name *");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel12.setText("Start Date");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        textMemberBirthday.setText("yyyy/mm/dd");
        textMemberBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMemberBirthdayActionPerformed(evt);
            }
        });
        getContentPane().add(textMemberBirthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 102, -1));
        getContentPane().add(textMemberFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 130, -1));

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        setBounds(0, 0, 604, 377);
    }// </editor-fold>//GEN-END:initComponents

    private void textMemberStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMemberStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMemberStartDateActionPerformed

    private void textMemberEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMemberEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMemberEmailActionPerformed

    private void textMemberBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMemberBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMemberBirthdayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(textMemberID.getText().equals("")){
            JOptionPane.showMessageDialog(null, " ID Number is a Mandotory field");            
        }else if(textMemberFName.getText().equals("")){
            JOptionPane.showMessageDialog(null, " First Name is a Mandotory field"); 
        }
        else if(textMemberLName.getText().equals("")){
            JOptionPane.showMessageDialog(null, " Last Name is a Mandotory field"); 
        }else{addMembers();}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textMemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMemberIDActionPerformed

    }//GEN-LAST:event_textMemberIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textMemberAircode;
    private javax.swing.JTextField textMemberBirthday;
    private javax.swing.JTextField textMemberCity;
    private javax.swing.JTextField textMemberCountry;
    private javax.swing.JTextField textMemberEmail;
    private javax.swing.JTextField textMemberFName;
    private javax.swing.JTextField textMemberHouseNumber;
    private javax.swing.JTextField textMemberID;
    private javax.swing.JTextField textMemberLName;
    private javax.swing.JTextField textMemberPhoneNumber;
    private javax.swing.JTextField textMemberStartDate;
    private javax.swing.JTextField textMemberStreet;
    // End of variables declaration//GEN-END:variables
}
